# This File is automatically synchronized from https://github.com/Glatzel/template

[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
lefthook-run = "lefthook run pre-commit --all-files --no-auto-install"

[dependencies]
actionlint = "==1.7.11"
cargo-machete = "==0.9.1"
lefthook = "==2.1.1"
markdownlint-cli2 = "==0.21.0"
numpydoc = "==1.10.0"
pre-commit-hooks = "==5.0.0"
python = "3.13.*"
ruff = "==0.15.1"
taplo = "==0.10.0"
typos = "==1.43.4"
